development:
  adapter: postgresql
  encoding: unicode
  database: wishthis_development
  pool: 5
  username: postgres
  password: 0s5perd5per!

test:
  adapter: postgresql
  encoding: unicode
  database: wishthis_development
  pool: 5
  username: postgres
  password: 0s5perd5per!

production:
  adapter: postgresql
  encoding: unicode
  database: wishthis_production
  pool: 5
  username: postgres
  password: 0s5perd5per!